spring.application.name=financial-api
server.port=8081

# CONEXÃO COM O SQL SERVER VIA VARIÁVEIS DE AMBIENTE
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=db_financial;encrypt=true;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Puxando o usuário e a senha das variáveis de ambiente
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate - Criar tabelas automaticamente e configurar SQL Server
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect